master:
  image: somendra11/debian-spark-python3.6-master
  command: bin/spark-class org.apache.spark.deploy.master.Master -h master
  hostname: master
  environment:
    MASTER: spark://master:7077
    SPARK_CONF_DIR: /conf
    SPARK_PUBLIC_DNS: 127.0.0.1 # can be replaced by master machine ip
  ports:
    - 9001:9001
    - 9002:9002
    - 9003:9003
    - 9004:9004
    - 9005:9005
    - 4040:4040
    - 8080:8080
    - 8022:8022
  volumes:
    - ./conf/master:/conf
    - ./data:/usr/spark-2.3.1/tmp
